const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("electronAPI", {
  getMinecraftVersions: () => ipcRenderer.invoke("get-minecraft-versions"),
  startBot: (host,port,version,auth,username) => ipcRenderer.invoke("start-bot", host,port,version,auth,username),
  stopFishing: () => ipcRenderer.invoke("stop-fishing"),
  stopFollowing: () => ipcRenderer.invoke("stop-following"),
  getBotSettings: () => ipcRenderer.invoke("get-bot-settings"),
  getActionSettings: () => ipcRenderer.invoke("get-bot-action-settings"),
  saveBotSettings: (data) => ipcRenderer.invoke("save-settings",data),
  saveBotActionSettings: (data) => ipcRenderer.invoke("save-action-settings",data),
  stopBot: () => ipcRenderer.invoke("stop-bot"),
  gameLogs: (callback) => ipcRenderer.on("game-logs", (_event, data) => callback(data)),
  botSkinData: (callback) => ipcRenderer.on("bot-skin", (_event, data) => callback(data)),
  log: (callback) => ipcRenderer.on("log",(_event,logMsg) => callback(logMsg)),
  initLoot: () => ipcRenderer.invoke("init-loot"),
  startFishing: () => ipcRenderer.invoke("start-fishing"),
  showError: (title,msg) => ipcRenderer.invoke("show-error",title,msg),
  followPlayer: (name) => ipcRenderer.invoke("follow-player",name),
  findWater: () => ipcRenderer.invoke("find-water"),
  depositLoot: () => ipcRenderer.invoke("deposit-loot"),
  getBotCommands: () => ipcRenderer.invoke("get-bot-commands"),
  stopCurrentTask: (task) => ipcRenderer.invoke("stop-current-task",task),
  dropLoot: (name) => ipcRenderer.invoke("drop-loot",name),
  showHelp: () => ipcRenderer.invoke("show-help"),
  sendMinecraftChatMessage: (message) => ipcRenderer.invoke("send-chat-message",message),
});
